<?php

    /**
     * This is the model class for table "{{users}}".
     *
     * The followings are the available columns in table '{{users}}':
     *
     * @property integer $id
     * @property string  $username
     * @property string  $password
     * @property string  $fullname
     * @property string  $email
     * @property string  $phone
     * @property integer $genre
     * @property string  $birthday
     * @property string  $address
     * @property string  $description
     * @property integer $status
     * @property string  $token
     * @property string  $avatar
     * @property string  $created_at
     * @property string  $updated_at
     * @property string  $cp_id
     * @property string  $is_admin
     */
    class AUsers extends Users
    {
        /**
         * @return array validation rules for model attributes.
         */
        public function rules()
        {
            // NOTE: you should only define rules for those attributes that
            // will receive user inputs.
            return array(
                array('id', 'verifyId'),
                array('id, username, password', 'required'),
                array('username', 'length', 'min' => 5, 'max' => 25, 'tooShort' => '{attribute} không được ngắn hơn 5 ký tự', 'tooLong' => '{attribute} không được dài quá 25 ký tự'),
                array('username', 'match', 'pattern' => '/^([a-z0-9_\.-])+$/', 'message' => "Chỉ chấp nhận các ký tự từ a->z, 0->9 và ký tự _ , ký tự - và dấu chấm"),
                array('genre, status', 'numerical', 'integerOnly' => TRUE),
                array('username, fullname, email, phone, id, birthday, address, description', 'length', 'max' => 255),
                array('password, token, avatar,cp_id, otp, is_admin', 'length', 'max' => 500),
                array('invite_code', 'length', 'max' => 20),
                array('created_at', 'safe'),
                array('email, phone', 'required'),
                array('email', 'email'),
                array('phone', 'authenticateMsisdn'),
                array('phone', 'unique', 'className' => 'Users', 'attributeName' => 'phone', 'message' => 'Số điện thoại này đã được đăng ký!', 'on' => 'api'),
                array('email', 'unique', 'className' => 'Users', 'attributeName' => 'email', 'message' => 'Email đã tồn tại!', 'on' => 'api'),
                // The following rule is used by search().
                // @todo Please remove those attributes that should not be searched.
                array('id, username, password, cp_id, is_admin, fullname, email, phone, genre, birthday, address, description, status, token, avatar, created_at, updated_at', 'safe', 'on' => 'search'),
            );
        }

        public function verifyId($attributes, $params)
        {
            if ($this->username) {
                $this->id = $this->genId(32);
                $user     = AUsers::model()->findByAttributes(array('id' => $this->id));
                if ($user) {
                    $this->verifyId($attributes, $params);
                } else {
                    return TRUE;
                }
            }

            return parent::tableName(); // TODO: Change the autogenerated stub
        }

        /**
         * @return array relational rules.
         */
        public function relations()
        {
            // NOTE: you may need to adjust the relation name and the related
            // class name for the relations automatically generated below.
            return array();
        }

        /**
         * @return array customized attribute labels (name=>label)
         */
        public function attributeLabels()
        {
            return array(
                'id'          => 'ID',
                'username'    => 'Tên đăng nhập',
                'password'    => 'Mật khẩu',
                'fullname'    => 'Têm đầy đủ',
                'email'       => 'Email',
                'phone'       => 'Số điện thoại',
                'genre'       => 'Giới tính',
                'birthday'    => 'Ngày sinh',
                'address'     => 'Địa chỉ',
                'description' => 'Mô tả',
                'status'      => 'Trạng thái',
                'token'       => 'Token',
                'avatar'      => 'Hình ảnh',
                'created_at'  => 'Ngày khởi tạo',
                'updated_at'  => 'Ngày cập nhật',
            );
        }

        /**
         * Retrieves a list of models based on the current search/filter conditions.
         *
         * Typical usecase:
         * - Initialize the model fields with values from filter form.
         * - Execute this method to get CActiveDataProvider instance which will filter
         * models according to data in model fields.
         * - Pass data provider to CGridView, CListView or any similar widget.
         *
         * @return CActiveDataProvider the data provider that can return the models
         * based on the search/filter conditions.
         */
        public function search()
        {
            // @todo Please modify the following code to remove attributes that should not be searched.

            $criteria = new CDbCriteria;

            $criteria->compare('id', $this->id);
            $criteria->compare('username', $this->username, TRUE);
            $criteria->compare('password', $this->password, TRUE);
            $criteria->compare('fullname', $this->fullname, TRUE);
            $criteria->compare('email', $this->email, TRUE);
            $criteria->compare('phone', $this->phone, TRUE);
            $criteria->compare('genre', $this->genre);
            $criteria->compare('birthday', $this->birthday, TRUE);
            $criteria->compare('address', $this->address, TRUE);
            $criteria->compare('description', $this->description, TRUE);
            $criteria->compare('status', $this->status);
            $criteria->compare('token', $this->token, TRUE);
            $criteria->compare('avatar', $this->avatar, TRUE);
            $criteria->compare('created_at', $this->created_at, TRUE);
            $criteria->compare('updated_at', $this->updated_at, TRUE);

            return new CActiveDataProvider($this, array(
                'criteria' => $criteria,
            ));
        }

        /**
         * Returns the static model of the specified AR class.
         * Please note that you should have this exact method in all your CActiveRecord descendants!
         *
         * @param string $className active record class name.
         *
         * @return Users the static model class
         */
        public static function model($className = __CLASS__)
        {
            return parent::model($className);
        }

        public static function genId($lengthChars = 32)
        {
            if ($lengthChars <= 0) {
                return FALSE;
            } else {
                $alphaString  = 'abcdefghijklmnopqrstuvwxyz';
                $numberString = '1234567890';

                $shuffleString = $alphaString . $numberString;
                $randomString  = substr(str_shuffle($shuffleString), 0, $lengthChars);
                $check         = AUsers::model()->findByAttributes(array('id' => $randomString));
                if ($check) {
                   return self::genId($lengthChars);
                }

                return $randomString;
            }
        }

    }

