<?php

    /**
     * Created by PhpStorm.
     * User: kienn
     * Date: 11/29/2017
     * Time: 4:07 PM
     */
    class ACampaignConfigs extends CampaignConfigs
    {
        const ACTIVE        = 1;
        const INACTIVE      = 0;
        const TEXT_ACTIVE   = 'Hiện';
        const TEXT_INACTIVE = 'Ẩn';

        public $new_link;

        /**
         * @return array customized attribute labels (name=>label)
         */
        public function attributeLabels()
        {
            return array(
                'id'           => 'ID',
                'utm_source'   => 'Utm Source',
                'utm_medium'   => 'Utm Medium',
                'utm_campaign' => 'Utm Campaign',
                'target_link'  => 'Target Link',
                'type'         => 'Loại',
                'create_date'  => 'Ngày tạo',
                'status'       => 'Trạng thái',
                'new_link'     => 'Tạo link',
            );
        }

        public function beforeSave()
        {
            if ($this->create_date) {
                $this->create_date = date("Y-m-d H:i:s", strtotime(str_replace('/', '-', $this->create_date)));
            }

            return parent::beforeSave(); // TODO: Change the autogenerated stub
        }

        /**
         * Returns the static model of the specified AR class.
         * Please note that you should have this exact method in all your CActiveRecord descendants!
         *
         * @param string $className active record class name.
         *
         * @return CampaignConfigs the static model class
         */
        public static function model($className = __CLASS__)
        {
            return parent::model($className);
        }
//
//        public function getCampaign($id)
//        {
//            $campaigns = ACampaignConfigs::model()->findByAttributes(array('id' =>$id));
//            if ($campaigns){
//                return $campaigns->name;
//            }
////            return
//        }
    }
